---
title: "QMM_Assignment4"
author: "Sharik Baig"
date: "23/09/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lpSolveAPI)
setwd("C:/Users/shari/OneDrive/Desktop/Business Analytics/QMM/Assignment4")
```

a linear program with 9 decision variables.

```{r}
lp <- make.lp(0,9, verbose = "neutral")
lp
```

Adding constraints

```{r}
add.constraint(lp, c(1,1,1,0,0,0,0,0,0), "<=", 750 )
add.constraint(lp, c(0,0,0,1,1,1,0,0,0), "<=", 900)
add.constraint(lp, c(0,0,0,0,0,0,1,1,1), "<=", 450)
add.constraint(lp, c(20,15,12,0,0,0,0,0,0), "<=", 13000)
add.constraint(lp, c(0,0,0,20,15,12,0,0,0), "<=", 12000)
add.constraint(lp, c(0,0,0,0,0,0,20,15,12), "<=", 5000)
add.constraint(lp, c(1,1,1,0,0,0,0,0,0), "<=", 900)
add.constraint(lp, c(0,0,0,1,1,1,0,0,0), "<=", 1200)
add.constraint(lp, c(0,0,0,0,0,0,1,1,1), "<=", 750)
add.constraint(lp, c(6, 6, 6, -5, -5, -5, 0, 0, 0), "=", 0)
add.constraint(lp, c( 3, 3, 3, 0, 0, 0, -5, -5, -5), "=", 0)
```

Create objective function.
We need maximum profit so change sense to max

```{r}
set.objfn(lp, c(420,360,300,420,360,300,420,360,300))
lp.control(lp, sense='max')
```

To identify the variables and constraints, Set the variable names and the constraints
set.bounds(lp, lower = c(0, 0, 0, 0, 0, 0, 0, 0, 0), columns = c(1,2,3,4,5,6,7,8,9)) 


```{r}
RowNames <- c("Con1", "Con2", "Con3", "storage1", "Storage2", "Storage33", "Sale1", "Sale2", "Sale3", "%C1", "%C2")
ColNames <- c("Large1", "Medium1", "Small1", "Large2", "Medium2", "Small2", "Large3", "Medium3", "Small3")
dimnames(lp) <- list(RowNames, ColNames)
lp
write.lp(lp, filename = "QMMAssignment4.lp", type = "lp")
solve(lp)
get.objective(lp)
get.variables(lp)
```